# This is a basic workflow that is manually triggered

name: Create Pastoral Care Request

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_call:
    inputs:
      ENV:
        required: true
        type: string
      MP_CLIENT_URL:
        required: true
        type: string
      MP_API_URL:
        required: true
        type: string
    secrets:
      MP_CLIENT_ID:
        required: true
      MP_CLIENT_SECRET:
        required: true
      
jobs:
  build:
    runs-on: ubuntu-latest
    environment: FreedomHouse Code ENV Vars
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create .env file
      run: |
        touch .env
        echo ENV=${{ inputs.ENV }} >> .env
        echo MP_CLIENT_URL=${{ inputs.MP_CLIENT_URL }} >> .env
        echo MP_API_URL=${{ inputs.MP_API_URL }} >> .env
        echo "MP_CLIENT_ID=${{ secrets.MP_CLIENT_ID }}" >> .env
        echo "MP_CLIENT_SECRET=${{ secrets.MP_CLIENT_SECRET }}" >> .env
    - name: Run main script
      run: python3 main.py
        